//
//  PCGitHubGraphics.h
//  GitHubClient
//
//  Created by Richard Lichkus on 7/18/14.
//  Copyright (c) 2014 CleverKnot LLC. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@class PCGradient;

@interface PCGitHubGraphics : NSObject

// iOS Controls Customization Outlets
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* threeBarMenuTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* userTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* repoTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* disabledButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* enabledButtonTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* lockedTargets;
@property(strong, nonatomic) IBOutletCollection(NSObject) NSArray* gitHubLoginTargets;

// Colors
+ (UIColor*)loginBlueColor;
+ (UIColor*)loginBlueColor2;

// Gradients
+ (PCGradient*)loginBlue;

// Images
+ (UIImage*)github_icon;

// Drawing Methods
+ (void)drawThreeBarMenu;
+ (void)drawUser;
+ (void)drawRepo;
+ (void)drawDisabledButton;
+ (void)drawEnabledButton;
+ (void)drawLocked;
+ (void)drawProgressBarWithRotation: (CGFloat)rotation;
+ (void)drawGitHubLogin;

// Generated Images
+ (UIImage*)imageOfThreeBarMenu;
+ (UIImage*)imageOfUser;
+ (UIImage*)imageOfRepo;
+ (UIImage*)imageOfDisabledButton;
+ (UIImage*)imageOfEnabledButton;
+ (UIImage*)imageOfLocked;
+ (UIImage*)imageOfGitHubLogin;

@end



@interface PCGradient : NSObject
@property(nonatomic, readonly) CGGradientRef CGGradient;
- (CGGradientRef)CGGradient NS_RETURNS_INNER_POINTER;

+ (instancetype)gradientWithColors: (NSArray*)colors locations: (const CGFloat*)locations;
+ (instancetype)gradientWithStartingColor: (UIColor*)startingColor endingColor: (UIColor*)endingColor;

@end
